---
title: "統計学を学ぶ大切さ"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ch01.md の目標

- データの解釈を批判的に見てみる
- データの比較に使う記述統計量を思い出す
- R言語を扱う動機を共有する

## 1.1 TV番組で流れる "実験" の怪しさ

データの解釈を批判的に見てみる練習をしましょう

1. 個人で(1)の第一パラグラフを読み、以下を行ってください。
   * **仮説**と**実験**、**結果**と**解釈**に整理してください。
   * 解釈が妥当か妥当でないか、根拠を考えて整理してください。
1. 4--5人のグループを作成し、ファシリテーターを決めます。
   グループ内で上記2つを確認して解釈が妥当かを議論し、まとめてください。
1. グループに対して意見を聞いていくので、
   ファシリテーターの方は報告してください。

## 1.1 TV番組で流れる "実験" の怪しさ

想定解答

1. 妥当でない(なにもしない比較対象のグループが必要)
1. 妥当でない(一人のデータからそんなに強く主張できない)
1. 妥当(上がったのは事実なので主張できる)

<!-- 議論で、何かが上がった下がったという主張のサポートは -->
<!-- 偶然じゃないのかとか、個人差じゃないのかとか、 -->
<!-- 色々な疑問が出てきて、安易には判断できないことがわかるのではないでしょうか。 -->

-> データを比較するときに大事な考え方を次に見ます。

<!-- 教科書の(2)は(1)とタスクは似ているのでスキップします(時間に余裕があれば着手)。 -->

## 1.2 平均とばらつきの療法が重要: 記述統計量

* データの選択（サンプリング）で「本当の値(平均)」からはズレる。
* 手元のデータのばらつきから、本当の平均の範囲を推定できれば議論できそう
  * 6年生女子の平均は 145--148 の間に95%の確率で入る
  * 6年生男子の平均は 144だった
  * → 同じグループであるという主張(仮説)を棄却する

## 1.3 統計を学ぶ大切さ: 推定・検定・予測

用語の説明と章との関連を示します。

1. 推定: 2, 3, 4章
1. 検定: 5, 6 章
1. 予測: 8, 9, 10 章

## Rの説明(pp.1--2)

* オープンソース
* 統計に強い
* 可視化も楽

## Ch01.md の目標

- データの解釈を批判的に見てみる -> 統計的に主張したい
- データの比較に使う記述統計量を思い出す -> ばらつきから本当の値の範囲をしりたい
- R言語を扱う動機を共有する -> 色々とメリットあり